
server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/back
    username: postgres
    password: 123456


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true